"""Reviewed built-in TDS records for the three products supplied by the user.

These records intentionally contain only applications supported by the source
documents.  Internal product grades are kept as document metadata and never
used as customer-discovery search terms.
"""
from __future__ import annotations

from typing import Any


BUILTIN_TDS_PRESETS: dict[str, dict[str, Any]] = {
    "nl-w1201": {
        "id": "nl-w1201",
        "title": "NL-W1201 水性表面处理剂",
        "material": "水性聚烯烃乳液 · 涂层底涂与附着力促进",
        "summary": "面向在 PP、PE、OPP、PET、ABS、PVC、玻璃、铝或木材上使用水性涂层的配方与加工企业。",
        "original_file_name": "Neon_Lion_NL-W1201_Water-Based_Surface_Treatment_Agent_TDS_EN.pdf",
        "document_version": "Rev. 01 · English Edition",
        "mime_type": "application/pdf",
        "byte_size": 83533,
        "content_sha256": "a5aca96c5c98f858ee9582831c67ba8ab47ab0030977867cf8fe09cc7ddad9e4",
        "extracted_summary": "Water-based polyolefin resin dispersion used as a coating primer and adhesion promoter. Recommended substrates: PET, PE, PP, OPP, ABS, PVC, glass, aluminum and wood. Primary use: adhesion promoter for untreated PP.",
        "applications": [
            {
                "application_name": "未处理 PP 基材的水性涂层底涂与附着力促进",
                "description": "在未处理聚丙烯表面先形成水性底涂层，改善后续涂层与低表面能基材之间的结合。",
                "substrate_or_object": "未经处理的 PP 基材",
                "material_function": "水性底涂、附着力促进",
                "evidence_excerpt": "PRIMARY USE: Adhesion promoter for untreated PP substrates.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["塑料水性涂料配方商", "PP 制品涂装加工企业", "工业底涂制造商"],
                "official_business_evidence": "官网应明确展示 PP 制品涂装、水性塑料涂料、聚丙烯表面处理或底涂工艺。",
                "exclusion_notes": "排除仅销售聚烯烃树脂、附着力促进剂或通用化工原料的供应商。",
                "search_terms": ["untreated polypropylene waterborne coating primer manufacturer", "PP plastic water based coating formulator", "polypropylene parts waterborne coating company"],
                "local_search_terms": ["polipropileno primer base água fabricante", "revestimento aquoso para PP fabricante"],
            },
            {
                "application_name": "PE、OPP、PET、ABS、PVC 塑料基材的水性涂层附着",
                "description": "作为水性涂层的底涂/附着促进组分，用于 TDS 明确列出的多种塑料基材。",
                "substrate_or_object": "PE、OPP、PET、ABS、PVC",
                "material_function": "改善水性涂层附着",
                "evidence_excerpt": "RECOMMENDED SUBSTRATES: PET / PE / PP / OPP / ABS / PVC, glass, aluminum and wood.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["塑料水性涂料制造商", "塑料件涂装企业", "涂布膜材加工企业"],
                "official_business_evidence": "官网应出现上述塑料基材之一，并展示水性涂层、底涂、涂布或表面处理业务。",
                "exclusion_notes": "不因公司生产塑料薄膜就判定使用该材料；必须同时看到涂层或表面处理证据。",
                "search_terms": ["waterborne coating for OPP PET PE manufacturer", "plastic substrate water based coating formulator", "coated OPP film waterborne coating company"],
                "local_search_terms": ["fabricante revestimento aquoso plástico", "recubrimiento base agua para plástico fabricante"],
            },
            {
                "application_name": "玻璃、铝和木材表面的水性涂层底涂",
                "description": "用于 TDS 推荐的非塑料基材，为水性涂层提供底涂和附着促进作用。",
                "substrate_or_object": "玻璃、铝、木材",
                "material_function": "水性涂层底涂、附着力促进",
                "evidence_excerpt": "It improves bonding between low-energy substrates and polar or non-polar materials, including PP, PE, OPP, ABS, PET, metal, glass and wood.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["水性工业涂料制造商", "金属或玻璃涂层加工企业", "水性木器涂料配方商"],
                "official_business_evidence": "官网应同时证明其使用水性涂层，并服务玻璃、铝或木材中的至少一种基材。",
                "exclusion_notes": "排除仅生产基材、没有涂层或配方业务证据的公司。",
                "search_terms": ["waterborne primer aluminum glass wood coating manufacturer", "water based industrial coating formulator aluminum", "waterborne adhesion primer glass coating company"],
                "local_search_terms": ["fabricante primer base água alumínio vidro madeira"],
            },
            {
                "application_name": "水性丙烯酸或聚氨酯乳液涂层体系的附着改性",
                "description": "作为与水性丙烯酸乳液、聚氨酯乳液兼容的聚烯烃树脂分散体，服务水性涂层配方。",
                "substrate_or_object": "水性丙烯酸乳液、聚氨酯乳液等水性产品",
                "material_function": "附着改性、配方相容组分",
                "evidence_excerpt": "COMPATIBILITY: Compatible with acrylic emulsions, polyurethane emulsions and other water-based products.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["水性涂料配方商", "水性聚氨酯涂层制造商", "水性丙烯酸涂层制造商"],
                "official_business_evidence": "官网应明确其自行配制或生产水性丙烯酸/聚氨酯涂层，而非只经销乳液原料。",
                "exclusion_notes": "排除纯树脂贸易商和仅销售通用乳液的原料供应商。",
                "search_terms": ["waterborne acrylic polyurethane coating formulator manufacturer", "water based coating adhesion promoter formulator", "waterborne industrial coating manufacturer acrylic polyurethane"],
                "local_search_terms": ["fabricante revestimento poliuretano acrílico base água"],
            },
        ],
    },
    "epoxidized-linseed-oil": {
        "id": "epoxidized-linseed-oil",
        "title": "环氧化亚麻籽油（ELO）",
        "material": "生物基增塑剂、稳定剂与反应型树脂改性添加剂",
        "summary": "面向自行进行聚合物配混，或生产涂料、胶黏剂、油墨、密封剂及改性树脂的企业。",
        "original_file_name": "TDS Epoxidized Linseed Oil(3).pdf",
        "document_version": "Technical Data Sheet",
        "mime_type": "application/pdf",
        "byte_size": 107827,
        "content_sha256": "0196c48415fcf3e7c75686d0d7401000698d5c2d1495d7e7eca00dbf93c628c3",
        "extracted_summary": "Bio-based functional additive used as an eco-friendly plasticizer and stabilizer in polymer systems, and in coatings, adhesives, inks, sealants and resin modification.",
        "applications": [
            {
                "application_name": "聚合物体系的生物基增塑与稳定",
                "description": "改善聚合物体系的柔韧性、加工性、热稳定性和耐老化性能。该 TDS 未限定为 PVC，搜索时不擅自缩窄树脂种类。",
                "substrate_or_object": "聚合物配混体系",
                "material_function": "环保增塑剂、稳定剂",
                "evidence_excerpt": "As an eco-friendly plasticizer and stabilizer, it can improve flexibility, processability, thermal stability and aging resistance.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["聚合物配混料制造商", "功能母粒制造商", "柔性聚合物制品配方企业"],
                "official_business_evidence": "官网应证明其具有聚合物配混、增塑或稳定配方能力，并生产相应制品或配混料。",
                "exclusion_notes": "排除只销售增塑剂、植物油或化工原料的贸易商；不把 PVC 当成 TDS 已确认事实。",
                "search_terms": ["bio based plasticizer polymer compound manufacturer", "polymer compounding thermal stabilizer manufacturer", "flexible polymer compound formulator"],
                "local_search_terms": ["fabricante composto polimérico plastificante biobased"],
            },
            {
                "application_name": "涂料体系的附着、韧性和耐化学性改性",
                "description": "利用反应型环氧基团改性涂料树脂，增强附着力、韧性和耐化学性。",
                "substrate_or_object": "涂料与涂层树脂体系",
                "material_function": "反应型树脂改性",
                "evidence_excerpt": "With reactive epoxy groups, it is also used in coatings ... and resin modification to enhance adhesion, toughness and chemical resistance.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["工业涂料制造商", "涂料树脂改性企业", "特种涂层配方商"],
                "official_business_evidence": "官网应展示自行生产涂料或进行树脂改性，并有附着、韧性或耐化学性相关产品说明。",
                "exclusion_notes": "排除仅经销涂料助剂或环氧化植物油的供应商。",
                "search_terms": ["industrial coating resin modifier manufacturer", "reactive epoxy additive coating formulator", "toughness adhesion chemical resistance coating manufacturer"],
                "local_search_terms": ["fabricante revestimento modificador resina epóxi"],
            },
            {
                "application_name": "胶黏剂与密封剂的反应型改性",
                "description": "用于胶黏剂和密封剂配方，以改善附着、韧性和耐化学性。",
                "substrate_or_object": "胶黏剂、密封剂",
                "material_function": "附着与韧性改性",
                "evidence_excerpt": "With reactive epoxy groups, it is also used in coatings, adhesives, inks, sealants and resin modification to enhance adhesion, toughness and chemical resistance.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["工业胶黏剂制造商", "密封剂制造商", "胶黏剂配方企业"],
                "official_business_evidence": "官网应证明其自行生产胶黏剂或密封剂，并展示配方性能或应用行业。",
                "exclusion_notes": "排除胶带转换商、施工服务商和纯原料贸易商。",
                "search_terms": ["industrial adhesive sealant manufacturer resin modifier", "reactive epoxy additive adhesive formulator", "sealant manufacturer toughness adhesion chemical resistance"],
                "local_search_terms": ["fabricante adesivo selante modificador resina"],
            },
            {
                "application_name": "油墨体系的树脂改性",
                "description": "在油墨配方中通过反应型环氧基团改善附着力、韧性和耐化学性。",
                "substrate_or_object": "印刷油墨体系",
                "material_function": "树脂改性、附着与韧性提升",
                "evidence_excerpt": "With reactive epoxy groups, it is also used in ... inks ... and resin modification to enhance adhesion, toughness and chemical resistance.",
                "evidence_page": 1,
                "evidence_status": "TDS明确",
                "target_company_types": ["印刷油墨制造商", "特种油墨配方商", "工业油墨制造商"],
                "official_business_evidence": "官网应证明其自行配制或制造油墨，并披露附着、耐化学或柔韧性能相关产品。",
                "exclusion_notes": "排除印刷厂、油墨经销商及通用颜料供应商。",
                "search_terms": ["printing ink manufacturer resin modification", "industrial ink formulator adhesion chemical resistance", "specialty ink manufacturer reactive additive"],
                "local_search_terms": ["fabricante tinta impressão modificador resina"],
            },
        ],
    },
    "fertilizer-coating": {
        "id": "fertilizer-coating",
        "title": "缓释肥料专用包膜剂",
        "material": "高分子改性缓释包膜原料 · 聚氨酯包膜应用",
        "summary": "面向生产缓/控释肥、包膜尿素、包膜复合肥和包膜有机肥，并具备喷涂包膜工艺的肥料企业。",
        "original_file_name": "缓释肥料专用包膜剂产品介绍(1)(1).docx",
        "document_version": "产品介绍",
        "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "byte_size": 16218,
        "content_sha256": "9d58761d8311c8b29902a8afb59e9e17810d831877ffb0e26c88e2998a6594eb",
        "extracted_summary": "高分子改性缓释包膜原料，可用于缓释肥、控释肥、包膜复合肥、尿素、高塔复合肥、普通复合肥及有机肥；兼容转鼓和流化床包膜设备。",
        "applications": [
            {
                "application_name": "缓释肥与控释肥的喷涂包膜生产",
                "description": "形成致密均匀膜层并调控养分释放，支持 30–180 天缓释周期。",
                "substrate_or_object": "缓释肥、控释肥颗粒",
                "material_function": "肥料包膜、养分释放调控",
                "process_conditions": "喷涂包膜；兼容转鼓、流化床等主流包膜设备；5 分钟成膜、1 小时完全固化。",
                "evidence_excerpt": "可广泛应用于缓释肥、控释肥……的包膜生产；可精准调控养分释放速率，支持 30-180 天缓释周期定制。",
                "evidence_status": "TDS明确",
                "target_company_types": ["缓释肥制造商", "控释肥制造商", "肥料包膜加工企业"],
                "official_business_evidence": "官网应明确展示自有缓释/控释肥产品及包膜、喷涂、转鼓或流化床生产能力。",
                "exclusion_notes": "排除普通肥料贸易商、农资零售商、包膜设备供应商和仅销售包膜原料的同行。",
                "search_terms": ["controlled release fertilizer manufacturer coating line", "slow release fertilizer producer coated granules", "fertilizer coating drum fluidized bed manufacturer"],
                "local_search_terms": ["fabricante fertilizante liberação controlada revestido", "fabricante adubo liberação lenta revestimento"],
            },
            {
                "application_name": "聚氨酯包膜尿素与定制释放周期尿素",
                "description": "用于生产聚氨酯包膜尿素，可定制 60、90、120 天释放周期。",
                "substrate_or_object": "尿素颗粒、聚氨酯包膜尿素",
                "material_function": "包膜控释",
                "process_conditions": "热包工艺；普通搅拌罐、抛光和标准化包膜流程；每吨尿素参考添加 8–10 kg。",
                "evidence_excerpt": "依托本包膜剂生产的聚氨酯包膜尿素……可定制 60 天、90 天、120 天不同释放周期。",
                "evidence_status": "TDS明确",
                "target_company_types": ["包膜尿素制造商", "控释尿素生产企业", "尿素深加工企业"],
                "official_business_evidence": "官网应出现 polymer/polyurethane coated urea、controlled-release urea 或明确的尿素包膜生产信息。",
                "exclusion_notes": "排除仅生产普通尿素且没有包膜/控释产品证据的公司。",
                "search_terms": ["polyurethane coated urea manufacturer", "polymer coated urea producer controlled release", "controlled release urea coating plant"],
                "local_search_terms": ["fabricante ureia revestida poliuretano", "ureia revestida liberação controlada fabricante"],
            },
            {
                "application_name": "包膜复合肥、高塔复合肥和普通复合肥",
                "description": "用于复合肥颗粒的包膜生产，形成耐运输、抗潮和缓释的薄膜层。",
                "substrate_or_object": "包膜复合肥、高塔复合肥、普通复合肥",
                "material_function": "颗粒包膜、防潮、缓释",
                "process_conditions": "喷涂均匀，适配大产能化肥生产线与转鼓/流化床设备。",
                "evidence_excerpt": "可广泛应用于……包膜复合肥、尿素、高塔复合肥、普通复合肥……的包膜生产。",
                "evidence_status": "TDS明确",
                "target_company_types": ["复合肥制造商", "NPK 肥料制造商", "高塔复合肥生产企业"],
                "official_business_evidence": "官网应证明其生产复合肥/NPK，并有 coated、controlled release、防潮包膜或包膜生产线证据。",
                "exclusion_notes": "排除只做散装掺混、分销或零售，且没有包膜产品/工艺证据的企业。",
                "search_terms": ["coated NPK fertilizer manufacturer", "coated compound fertilizer producer", "compound fertilizer manufacturer coating line"],
                "local_search_terms": ["fabricante fertilizante NPK revestido", "fertilizante composto revestido fabricante"],
            },
            {
                "application_name": "有机肥颗粒的包膜与缓释改性",
                "description": "用于有机肥颗粒包膜，改善防潮、耐运输和养分缓释性能。",
                "substrate_or_object": "有机肥颗粒",
                "material_function": "颗粒包膜、缓释、防潮",
                "process_conditions": "适配喷涂及常见包膜设备；需按肥料品类和工艺进行配方确认。",
                "evidence_excerpt": "可广泛应用于缓释肥、控释肥、包膜复合肥、尿素、高塔复合肥、普通复合肥及有机肥的包膜生产。",
                "evidence_status": "TDS明确",
                "target_company_types": ["颗粒有机肥制造商", "有机复合肥制造商", "包膜有机肥生产企业"],
                "official_business_evidence": "官网应同时证明颗粒有机肥生产与包膜/缓释/控释产品或工艺。",
                "exclusion_notes": "排除堆肥场、散装有机肥经销商和没有颗粒包膜证据的企业。",
                "search_terms": ["coated organic fertilizer granule manufacturer", "controlled release organic fertilizer producer", "organic compound fertilizer coating manufacturer"],
                "local_search_terms": ["fabricante fertilizante orgânico granulado revestido"],
            },
        ],
    },
}


def builtin_tds_preset(preset_id: str) -> dict[str, Any] | None:
    return BUILTIN_TDS_PRESETS.get(preset_id)


def builtin_tds_preset_summaries() -> list[dict[str, Any]]:
    return [
        {
            "id": preset["id"],
            "title": preset["title"],
            "material": preset["material"],
            "summary": preset["summary"],
            "original_file_name": preset["original_file_name"],
            "document_version": preset["document_version"],
            "application_count": len(preset["applications"]),
            "applications": [
                {
                    "application_name": item["application_name"],
                    "description": item["description"],
                    "target_company_types": item["target_company_types"],
                }
                for item in preset["applications"]
            ],
        }
        for preset in BUILTIN_TDS_PRESETS.values()
    ]
