import type { Customer, Followup, Product } from './types'

export const customers: Customer[] = [
  { id: 'c1', company_name: 'Uflex', country: 'India', contact_person: 'Dileep', email: 'dileep@uflex.co.in', whatsapp: '+91 98 221 8608', product_interest: 'NL-007', application: 'PPC Film / Food Packaging', customer_stage: 'Sample Payment Pending', priority: 'HIGH', status_label: '等待样品付款', status_tone: 'warning', last_contact_date: '2026-08-20', next_followup_date: '2026-08-22', notes: 'PPC Film / Cast Film / Food Packaging / Fresh Keeping Film', requirements: ['MFR 5–7', 'Film Thickness 20–30μm', 'OTR < 5', 'WVTR < 5'], current_progress: ['客户已确认性能指标', '25kg 样品需求', '样品 + 快递：USD 310'], next_action: ['发送 PI', 'QTY：1 bag', '确认付款'], sample_status: 'Sample payment pending · 25kg', created_at: '2026-08-08' },
  { id: 'c2', company_name: 'Agrileaf', country: 'India', contact_person: 'Vaibhav', email: 'vaibhav@agrileaf.in', whatsapp: '+91 97 552 3901', product_interest: 'NL-PHA-21', application: 'Water-based Barrier Coating', customer_stage: 'Sample Payment', priority: 'HIGH', status_label: '等待付款', status_tone: 'warning', last_contact_date: '2026-08-18', next_followup_date: '2026-08-21', notes: '5kg Sample', requirements: ['5kg Sample'], current_progress: ['客户已提供收货地址', 'Sample + Express：USD 150'], next_action: ['确认付款', '安排寄样', '上传快递单号'], sample_status: 'Waiting payment · 5kg sample', created_at: '2026-08-05' },
  { id: 'c3', company_name: 'Flexo', country: 'Philippines', contact_person: 'Joselito', email: 'joselito@flexo.ph', whatsapp: '+63 917 555 0190', product_interest: 'E4050 Replacement Project', application: 'Glassine Extrusion Coating', customer_stage: 'Technical Testing', priority: 'HIGH', status_label: '等待客户样品', status_tone: 'attention', last_contact_date: '2026-08-20', next_followup_date: '2026-08-25', notes: '终端：Cheese Packaging', project_background: ['Replace: Henkel Proxmelt E4050', 'Process: Extrusion coating', 'Need: Adhesion test / Heat resistance / Bond strength'], monthly_consumption: '2.5 tons', current_progress: ['已发送替代产品 TDS', '等待客户寄原料样品'], next_action: ['Receive customer sample', 'Prepare 2kg test sample', 'Lab evaluation'], sample_status: 'Waiting for customer material sample', created_at: '2026-07-28', timeline: [{ date: '2026-08-10', title: 'Customer sent TDS' }, { date: '2026-08-12', title: 'Confirmed application' }, { date: '2026-08-15', title: 'Sent alternative product information' }, { date: '2026-08-20', title: 'Waiting customer sample' }] },
  { id: 'c4', company_name: 'FLEX Design', country: 'Netherlands', contact_person: 'Dominic', email: 'dominic@flexdesign.nl', whatsapp: '+31 6 1890 3033', product_interest: 'NL-PHA-21', application: 'PFAS-free Paper Cup Barrier Coating', customer_stage: 'Technical Confirmation', priority: 'MEDIUM HIGH', status_label: '等待客户确认样品', status_tone: 'warning', last_contact_date: '2026-08-19', next_followup_date: '2026-08-26', notes: 'Process: Spray / Dip Coating', requirements: ['Acid resistance', 'Tomato sauce resistance', 'Film formation temperature', 'Drying condition'], current_progress: ['TDS sent', 'Technical questions answered'], next_action: ['Confirm sample', 'Prepare 1–2L sample'], sample_status: 'Technical confirmation', created_at: '2026-08-02' },
  { id: 'c5', company_name: 'ATSajan', country: 'Thailand', contact_person: 'Anchasa', email: 'anchasa@atsajan.co.th', whatsapp: '+66 81 553 2871', product_interest: 'MCPP', application: 'Polypropylene Adhesion Modification', customer_stage: 'Maintain Relationship', priority: 'MEDIUM', status_label: '长期维护', status_tone: 'success', last_contact_date: '2026-08-16', next_followup_date: '2026-09-02', notes: 'Liquid MCPP', requirements: ['Liquid MCPP', 'Potential demand: 20 tons/year', 'Customer accepts: 6 months shelf life'], current_progress: ['Factory evaluation pending'], next_action: ['Keep contact', 'Update when factory progress available'], created_at: '2026-06-18' },
  { id: 'c6', company_name: 'Inkofix', country: 'India', contact_person: 'LN Garg', email: 'lngarg@inkofix.in', whatsapp: '+91 99 871 1640', product_interest: 'NL-PHA-21', application: 'Water-based Barrier Coating', customer_stage: 'Quotation', priority: 'MEDIUM HIGH', status_label: 'Price Discussion', status_tone: 'attention', last_contact_date: '2026-08-15', next_followup_date: '2026-08-28', notes: '客户反馈：Price is high', quotation: ['USD 5,550/T CIF Mundra', 'Packing: 1000kg IBC', 'Container: 18 tons / 20GP'], current_progress: ['报价已发送', '客户认为价格偏高'], next_action: ['确认 Heat sealing requirement', 'Temperature / Pressure / Time', 'Substrate / Required strength'], created_at: '2026-07-15' },
]

export const followups: Followup[] = [
  { id: 'f1', customer_id: 'c1', date: '2026-08-20', content: '客户已确认 PPC Film 性能指标，准备 25kg 样品。', next_action: '发送 PI 并确认 USD 310 样品付款', status: 'Open' },
  { id: 'f2', customer_id: 'c2', date: '2026-08-18', content: 'Vaibhav 已提供收货地址，等待 5kg 样品付款。', next_action: '确认 USD 150 付款并安排寄样', status: 'Open' },
  { id: 'f3', customer_id: 'c3', date: '2026-08-20', content: '已发送替代产品资料，等待 Flexo 寄送原料样品。', next_action: '收样后准备 2kg 测试样品', status: 'Open' },
]

export const products: Product[] = [
  { id: 'p1', product_name: 'NL-007', product_code: 'NL-007', category: 'Barrier Masterbatch', application: 'PPC Film', description: '用于食品包装与保鲜膜的阻隔母粒，覆盖 Cast Film 等应用。', notes: 'Active' },
  { id: 'p2', product_name: 'NL-PHA-21', product_code: 'NL-PHA-21', category: 'Water-based Barrier Coating', application: 'Paper Packaging', description: '水性阻隔涂层，适用于纸包装及 PFAS-free 纸杯体系。', notes: 'Agrileaf · FLEX Design · Inkofix' },
  { id: 'p3', product_name: 'HM-800', product_code: 'HM-800', category: 'Bio-based Polyester Plasticizer', application: 'PVC Film · Wire & Cable · Flexible Hose', description: '生物基聚酯增塑剂，兼顾材料柔韧性与低迁移表现。', notes: 'Active' },
  { id: 'p4', product_name: 'ESO', product_code: 'ESO', category: 'Epoxidized Soybean Oil', application: 'PVC Plasticizer', description: '环保型环氧大豆油，用于 PVC 增塑与稳定体系。', notes: 'Active' },
  { id: 'p5', product_name: 'MCPP', product_code: 'MCPP', category: 'Maleic Anhydride Modified Chlorinated Polypropylene', application: 'Adhesion Promoter', description: '马来酸酐改性氯化聚丙烯，用于 PP 基材的附着力改善。', notes: 'Active' },
]
